"""
Django settings for model_agency project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "phonenumber_field",
    "model",
    "contact",
    "core"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'model_agency.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'model_agency.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "model.User"


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": (
                "{pathname}: [{asctime}] {levelname}."
                " Logger '{name}' '{message}'"
            ),
            "style": "{",
            "date_fmt": "%d/%b/%Y %H:%M:%S"
        },
        "simple": {
            "format": "{pathname} {message}",
            "style": "{"
        }
    },
    "filters": {
        "debug_true": {
            "()": "django.utils.log.RequireDebugTrue"
        },
        "debug_false": {
            "()": "django.utils.log.RequireDebugFalse"
        },
    },
    "handlers": {
        "console": {  # handler without any filters
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "simple",
        },
        "console_debug_true": {  # handler when DEBUG is True
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "simple",
            "filters": ["debug_true"]
        },
        "console_debug_false": {  # handler when DEBUG is False
            "class": "logging.StreamHandler",
            "level": "INFO",
            "formatter": "verbose",
            "filters": ["debug_false"]
        },
        # Writing Model app logs to files, which
        # are rotating every midnight, total number of
        # files are `backupCount`
        "file_model_debug_false": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "level": "INFO",
            "filename": "logs/model_app/model.log",
            "backupCount": 5,
            "when": "midnight",
            "formatter": "verbose",
            "filters": ["debug_false"]
        }
    },
    "loggers": {
        "model.tests": {
            "level": "INFO",
            "handlers": ["console"]
        },
        "model_app": {
            # Some logs message are DEBUG and some are INFO
            # that why we are using 3 handlers during development
            # and production, handlers will determine where to go
            # base on level of severity
            "handlers": [
                "console_debug_true",
                "console_debug_false",
                "file_model_debug_false"
            ],
            "level": "DEBUG"
        }

    }
}
