# Generated by Django 5.1.4 on 2025-02-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact", "0001_initial"),
        ("model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="model.model",
            ),
        ),
    ]
